[package]
name = "lsp-client"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2021"

[dependencies]
serde_json = "1.0"
jsonrpc-lite = "0.6"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
